#server:
#  port: 26

#spring:
#  data:
#    mongodb:
#      database: tools
#      host: localhost
#      port: 27018

spring:
  data:
    mongodb:
      database: tools
      host: my-mongodb-s
      port: 27017